version: '3'

services:
  etcd:
    image: 'bitnami/etcd:3.5.12'
    container_name: etcd
#    restart: always
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ETCD_ENABLE_V2=true
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://192.168.1.103:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_NAME=etcd
    volumes:
      - ./components/etcd/data:/bitnami/etcd/data
      - ./components/etcd/logs:/bitnami/etcd/logs
    networks:
      easy-chat:

  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    container_name: redis
    volumes:
      - ./components/redis/data:/data
      - ./components/redis/config/redis.conf:/usr/local/redis/config/redis.conf
    environment:
      TZ: Asia/Shanghai
    privileged: true
#    restart: always
    networks:
      easy-chat:
    command: redis-server /usr/local/redis/config/redis.conf
#
  mongo:
    image: 'mongo:4.0'
    container_name: mongo
#    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: easy-chat
    ports:
      - "27017:27017"
    volumes:
      - ./components/mongo/data:/data/db
      - /etc/locatime:/etc/locatime
    networks:
      easy-chat:

  zookeeper:
    image: 'zookeeper:3.9.2'
    ports:
      - "2181:2181"
    container_name: zookeeper
    volumes:
      - /etc/localtime:/etc/localtime
      - ./components/zookeeper/data:/var/lib/zookeeper/data
      - ./components/zookeeper/log:/var/lib/zookeeper/log
    environment:
      TZ: Asia/Shanghai
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_PORT_NUMBER: 2181
#    restart: always
    networks:
      easy-chat:

  kafka:
    image: 'bitnami/kafka:3.3.2'
#    restart: always
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      TZ: Asia/Shanghai
      KAFKA_BROKER_ID: 0
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.103:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: 192.168.1.103:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - ./components/kafka/data:/bitnami/kafka/data
#      - ./components/kafka/config:/opt/bitnami/kafka/config #打开后kafka异常，无法启动
      - ./components/kafka/logs:/opt/bitnami/kafka/logs
    depends_on:
      - zookeeper
    networks:
      easy-chat:

#  mysql:
#    image: mysql:8.3.0
#    ports:
#      - "3306:3306"
#    container_name: mysql
#    volumes:
#      - ./components/mysql/data:/var/lib/mysql
#      - /etcd/localtime:/etc/localtime
#    command:
#      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
#      --default-authentication-plugin=mysql_native_password
#      --character-set-server=utf8mb4
#      --collation-server=utf8mb4_general_ci
#      --explicit_defaults_for_timestamp=true
#      --lower_case_table_names=1
#    environment:
#      MYSQL_ROOT_PASSWORD: a12Cd3_45pUq6
#    restart: always
#    networks:
#      easy-chat:

networks:
  easy-chat:
    driver: bridge